version: '3'
services:
  grafana1:
    image: grafana/grafana:latest
    container_name: grafana1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data1:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana2:
    image: grafana/grafana:latest
    container_name: grafana2
    ports:
      - "3001:3000"
    volumes:
      - grafana_data2:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  grafana_data1:
  grafana_data2:
