version: '3'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data1:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    volumes:
      - cassandra_data2:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CONTACT_POINTS=cassandra1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    volumes:
      - cassandra_data3:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CONTACT_POINTS=cassandra1
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q 'UN'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra_data1:
  cassandra_data2:
  cassandra_data3:
